### ISSUE TITLE
BepinEx support

### ISSUE THREAD

**Issue by Akelaphobia** [AzeTheGreat/GYK-Mods#1]
Could you update your judder fix mod for BepinEx since other modders have moved over to that instead of QMod? From what I understand you can't use both at the same time, so at the moment I can't use the judder fix, but I'd love to since it's quite distracting.

**Comment by AzeTheGreat** [comment]
Updated in 9259dbfb5b851219bd666156c09685f0c48aca0b.  This is available on this repo or Nexus Mods.
